/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdPersuasiveness = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type AdType = { 'fastFood' : null } |
  { 'snacks' : null } |
  { 'sugaryDrinks' : null };
export type AgeGroup = { '_19plus' : null } |
  { '_16to18' : null } |
  { '_13to15' : null };
export type ConcernLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Frequency = { 'often' : null } |
  { 'rare' : null } |
  { 'sometimes' : null };
export type Gender = { 'female' : null } |
  { 'male' : null };
export type Platform = { 'tv' : null } |
  { 'instagram' : null } |
  { 'multiple' : null } |
  { 'youtube' : null };
export interface Prediction {
  'userId' : Principal,
  'adPersuasiveness' : AdPersuasiveness,
  'platform' : Platform,
  'adType' : AdType,
  'concernLevel' : ConcernLevel,
  'gender' : Gender,
  'timestamp' : bigint,
  'frequency' : Frequency,
  'screenTime' : ScreenTime,
  'recommendation' : string,
  'ageGroup' : AgeGroup,
}
export type ScreenTime = { 'over5hrs' : null } |
  { 'under2hrs' : null } |
  { '_2to5hrs' : null };
export interface _SERVICE {
  'getAllPredictions' : ActorMethod<[], Array<Prediction>>,
  'getConcernDistribution' : ActorMethod<
    [],
    { 'low' : bigint, 'high' : bigint, 'medium' : bigint }
  >,
  'getPredictionCount' : ActorMethod<[], bigint>,
  'getPredictionsByAgeGroup' : ActorMethod<[AgeGroup], Array<Prediction>>,
  'getPredictionsByConcernLevel' : ActorMethod<
    [ConcernLevel],
    Array<Prediction>
  >,
  'getPredictionsByGender' : ActorMethod<[Gender], Array<Prediction>>,
  'submitPrediction' : ActorMethod<
    [
      AgeGroup,
      Gender,
      ScreenTime,
      Platform,
      Frequency,
      AdType,
      AdPersuasiveness,
    ],
    [ConcernLevel, string]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];