/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdPersuasiveness = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Platform = IDL.Variant({
  'tv' : IDL.Null,
  'instagram' : IDL.Null,
  'multiple' : IDL.Null,
  'youtube' : IDL.Null,
});
export const AdType = IDL.Variant({
  'fastFood' : IDL.Null,
  'snacks' : IDL.Null,
  'sugaryDrinks' : IDL.Null,
});
export const ConcernLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const Frequency = IDL.Variant({
  'often' : IDL.Null,
  'rare' : IDL.Null,
  'sometimes' : IDL.Null,
});
export const ScreenTime = IDL.Variant({
  'over5hrs' : IDL.Null,
  'under2hrs' : IDL.Null,
  '_2to5hrs' : IDL.Null,
});
export const AgeGroup = IDL.Variant({
  '_19plus' : IDL.Null,
  '_16to18' : IDL.Null,
  '_13to15' : IDL.Null,
});
export const Prediction = IDL.Record({
  'userId' : IDL.Principal,
  'adPersuasiveness' : AdPersuasiveness,
  'platform' : Platform,
  'adType' : AdType,
  'concernLevel' : ConcernLevel,
  'gender' : Gender,
  'timestamp' : IDL.Int,
  'frequency' : Frequency,
  'screenTime' : ScreenTime,
  'recommendation' : IDL.Text,
  'ageGroup' : AgeGroup,
});

export const idlService = IDL.Service({
  'getAllPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  'getConcernDistribution' : IDL.Func(
      [],
      [IDL.Record({ 'low' : IDL.Nat, 'high' : IDL.Nat, 'medium' : IDL.Nat })],
      ['query'],
    ),
  'getPredictionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPredictionsByAgeGroup' : IDL.Func(
      [AgeGroup],
      [IDL.Vec(Prediction)],
      ['query'],
    ),
  'getPredictionsByConcernLevel' : IDL.Func(
      [ConcernLevel],
      [IDL.Vec(Prediction)],
      ['query'],
    ),
  'getPredictionsByGender' : IDL.Func(
      [Gender],
      [IDL.Vec(Prediction)],
      ['query'],
    ),
  'submitPrediction' : IDL.Func(
      [
        AgeGroup,
        Gender,
        ScreenTime,
        Platform,
        Frequency,
        AdType,
        AdPersuasiveness,
      ],
      [ConcernLevel, IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdPersuasiveness = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'tv' : IDL.Null,
    'instagram' : IDL.Null,
    'multiple' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const AdType = IDL.Variant({
    'fastFood' : IDL.Null,
    'snacks' : IDL.Null,
    'sugaryDrinks' : IDL.Null,
  });
  const ConcernLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const Frequency = IDL.Variant({
    'often' : IDL.Null,
    'rare' : IDL.Null,
    'sometimes' : IDL.Null,
  });
  const ScreenTime = IDL.Variant({
    'over5hrs' : IDL.Null,
    'under2hrs' : IDL.Null,
    '_2to5hrs' : IDL.Null,
  });
  const AgeGroup = IDL.Variant({
    '_19plus' : IDL.Null,
    '_16to18' : IDL.Null,
    '_13to15' : IDL.Null,
  });
  const Prediction = IDL.Record({
    'userId' : IDL.Principal,
    'adPersuasiveness' : AdPersuasiveness,
    'platform' : Platform,
    'adType' : AdType,
    'concernLevel' : ConcernLevel,
    'gender' : Gender,
    'timestamp' : IDL.Int,
    'frequency' : Frequency,
    'screenTime' : ScreenTime,
    'recommendation' : IDL.Text,
    'ageGroup' : AgeGroup,
  });
  
  return IDL.Service({
    'getAllPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
    'getConcernDistribution' : IDL.Func(
        [],
        [IDL.Record({ 'low' : IDL.Nat, 'high' : IDL.Nat, 'medium' : IDL.Nat })],
        ['query'],
      ),
    'getPredictionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPredictionsByAgeGroup' : IDL.Func(
        [AgeGroup],
        [IDL.Vec(Prediction)],
        ['query'],
      ),
    'getPredictionsByConcernLevel' : IDL.Func(
        [ConcernLevel],
        [IDL.Vec(Prediction)],
        ['query'],
      ),
    'getPredictionsByGender' : IDL.Func(
        [Gender],
        [IDL.Vec(Prediction)],
        ['query'],
      ),
    'submitPrediction' : IDL.Func(
        [
          AgeGroup,
          Gender,
          ScreenTime,
          Platform,
          Frequency,
          AdType,
          AdPersuasiveness,
        ],
        [ConcernLevel, IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };