/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Prediction {
    userId: Principal;
    adPersuasiveness: AdPersuasiveness;
    platform: Platform;
    adType: AdType;
    concernLevel: ConcernLevel;
    gender: Gender;
    timestamp: bigint;
    frequency: Frequency;
    screenTime: ScreenTime;
    recommendation: string;
    ageGroup: AgeGroup;
}
export enum AdType {
    fastFood = "fastFood",
    snacks = "snacks",
    sugaryDrinks = "sugaryDrinks"
}
export enum AgeGroup {
    _19plus = "_19plus",
    _16to18 = "_16to18",
    _13to15 = "_13to15"
}
export enum ConcernLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum Frequency {
    often = "often",
    rare = "rare",
    sometimes = "sometimes"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Platform {
    tv = "tv",
    instagram = "instagram",
    multiple = "multiple",
    youtube = "youtube"
}
export enum ScreenTime {
    over5hrs = "over5hrs",
    under2hrs = "under2hrs",
    _2to5hrs = "_2to5hrs"
}
export interface backendInterface {
    getAllPredictions(): Promise<Array<Prediction>>;
    getConcernDistribution(): Promise<{
        low: bigint;
        high: bigint;
        medium: bigint;
    }>;
    getPredictionCount(): Promise<bigint>;
    getPredictionsByAgeGroup(ageGroup: AgeGroup): Promise<Array<Prediction>>;
    getPredictionsByConcernLevel(concernLevel: ConcernLevel): Promise<Array<Prediction>>;
    getPredictionsByGender(gender: Gender): Promise<Array<Prediction>>;
    submitPrediction(ageGroup: AgeGroup, gender: Gender, screenTime: ScreenTime, platform: Platform, frequency: Frequency, adType: AdType, adPersuasiveness: AdPersuasiveness): Promise<[ConcernLevel, string]>;
}
import type { AdPersuasiveness as _AdPersuasiveness, AdType as _AdType, AgeGroup as _AgeGroup, ConcernLevel as _ConcernLevel, Frequency as _Frequency, Gender as _Gender, Platform as _Platform, Prediction as _Prediction, ScreenTime as _ScreenTime } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllPredictions(): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPredictions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPredictions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConcernDistribution(): Promise<{
        low: bigint;
        high: bigint;
        medium: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getConcernDistribution();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConcernDistribution();
            return result;
        }
    }
    async getPredictionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionCount();
            return result;
        }
    }
    async getPredictionsByAgeGroup(arg0: AgeGroup): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionsByAgeGroup(to_candid_AgeGroup_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionsByAgeGroup(to_candid_AgeGroup_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictionsByConcernLevel(arg0: ConcernLevel): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionsByConcernLevel(to_candid_ConcernLevel_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionsByConcernLevel(to_candid_ConcernLevel_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictionsByGender(arg0: Gender): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionsByGender(to_candid_Gender_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionsByGender(to_candid_Gender_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPrediction(arg0: AgeGroup, arg1: Gender, arg2: ScreenTime, arg3: Platform, arg4: Frequency, arg5: AdType, arg6: AdPersuasiveness): Promise<[ConcernLevel, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPrediction(to_candid_AgeGroup_n19(this._uploadFile, this._downloadFile, arg0), to_candid_Gender_n23(this._uploadFile, this._downloadFile, arg1), to_candid_ScreenTime_n25(this._uploadFile, this._downloadFile, arg2), to_candid_Platform_n27(this._uploadFile, this._downloadFile, arg3), to_candid_Frequency_n29(this._uploadFile, this._downloadFile, arg4), to_candid_AdType_n31(this._uploadFile, this._downloadFile, arg5), to_candid_AdPersuasiveness_n33(this._uploadFile, this._downloadFile, arg6));
                return [
                    from_candid_ConcernLevel_n10(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPrediction(to_candid_AgeGroup_n19(this._uploadFile, this._downloadFile, arg0), to_candid_Gender_n23(this._uploadFile, this._downloadFile, arg1), to_candid_ScreenTime_n25(this._uploadFile, this._downloadFile, arg2), to_candid_Platform_n27(this._uploadFile, this._downloadFile, arg3), to_candid_Frequency_n29(this._uploadFile, this._downloadFile, arg4), to_candid_AdType_n31(this._uploadFile, this._downloadFile, arg5), to_candid_AdPersuasiveness_n33(this._uploadFile, this._downloadFile, arg6));
            return [
                from_candid_ConcernLevel_n10(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
}
function from_candid_AdPersuasiveness_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdPersuasiveness): AdPersuasiveness {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_AdType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdType): AdType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AgeGroup_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeGroup): AgeGroup {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ConcernLevel_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConcernLevel): ConcernLevel {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Frequency_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frequency): Frequency {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Prediction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prediction): Prediction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ScreenTime_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScreenTime): ScreenTime {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    adPersuasiveness: _AdPersuasiveness;
    platform: _Platform;
    adType: _AdType;
    concernLevel: _ConcernLevel;
    gender: _Gender;
    timestamp: bigint;
    frequency: _Frequency;
    screenTime: _ScreenTime;
    recommendation: string;
    ageGroup: _AgeGroup;
}): {
    userId: Principal;
    adPersuasiveness: AdPersuasiveness;
    platform: Platform;
    adType: AdType;
    concernLevel: ConcernLevel;
    gender: Gender;
    timestamp: bigint;
    frequency: Frequency;
    screenTime: ScreenTime;
    recommendation: string;
    ageGroup: AgeGroup;
} {
    return {
        userId: value.userId,
        adPersuasiveness: from_candid_AdPersuasiveness_n4(_uploadFile, _downloadFile, value.adPersuasiveness),
        platform: from_candid_Platform_n6(_uploadFile, _downloadFile, value.platform),
        adType: from_candid_AdType_n8(_uploadFile, _downloadFile, value.adType),
        concernLevel: from_candid_ConcernLevel_n10(_uploadFile, _downloadFile, value.concernLevel),
        gender: from_candid_Gender_n11(_uploadFile, _downloadFile, value.gender),
        timestamp: value.timestamp,
        frequency: from_candid_Frequency_n13(_uploadFile, _downloadFile, value.frequency),
        screenTime: from_candid_ScreenTime_n15(_uploadFile, _downloadFile, value.screenTime),
        recommendation: value.recommendation,
        ageGroup: from_candid_AgeGroup_n17(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    often: null;
} | {
    rare: null;
} | {
    sometimes: null;
}): Frequency {
    return "often" in value ? Frequency.often : "rare" in value ? Frequency.rare : "sometimes" in value ? Frequency.sometimes : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    over5hrs: null;
} | {
    under2hrs: null;
} | {
    _2to5hrs: null;
}): ScreenTime {
    return "over5hrs" in value ? ScreenTime.over5hrs : "under2hrs" in value ? ScreenTime.under2hrs : "_2to5hrs" in value ? ScreenTime._2to5hrs : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _19plus: null;
} | {
    _16to18: null;
} | {
    _13to15: null;
}): AgeGroup {
    return "_19plus" in value ? AgeGroup._19plus : "_16to18" in value ? AgeGroup._16to18 : "_13to15" in value ? AgeGroup._13to15 : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ConcernLevel {
    return "low" in value ? ConcernLevel.low : "high" in value ? ConcernLevel.high : "medium" in value ? ConcernLevel.medium : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tv: null;
} | {
    instagram: null;
} | {
    multiple: null;
} | {
    youtube: null;
}): Platform {
    return "tv" in value ? Platform.tv : "instagram" in value ? Platform.instagram : "multiple" in value ? Platform.multiple : "youtube" in value ? Platform.youtube : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fastFood: null;
} | {
    snacks: null;
} | {
    sugaryDrinks: null;
}): AdType {
    return "fastFood" in value ? AdType.fastFood : "snacks" in value ? AdType.snacks : "sugaryDrinks" in value ? AdType.sugaryDrinks : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prediction>): Array<Prediction> {
    return value.map((x)=>from_candid_Prediction_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AdPersuasiveness_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdPersuasiveness): _AdPersuasiveness {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_AdType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdType): _AdType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_AgeGroup_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): _AgeGroup {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ConcernLevel_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernLevel): _ConcernLevel {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Frequency_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ScreenTime_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScreenTime): _ScreenTime {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): {
    _19plus: null;
} | {
    _16to18: null;
} | {
    _13to15: null;
} {
    return value == AgeGroup._19plus ? {
        _19plus: null
    } : value == AgeGroup._16to18 ? {
        _16to18: null
    } : value == AgeGroup._13to15 ? {
        _13to15: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == ConcernLevel.low ? {
        low: null
    } : value == ConcernLevel.high ? {
        high: null
    } : value == ConcernLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScreenTime): {
    over5hrs: null;
} | {
    under2hrs: null;
} | {
    _2to5hrs: null;
} {
    return value == ScreenTime.over5hrs ? {
        over5hrs: null
    } : value == ScreenTime.under2hrs ? {
        under2hrs: null
    } : value == ScreenTime._2to5hrs ? {
        _2to5hrs: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    tv: null;
} | {
    instagram: null;
} | {
    multiple: null;
} | {
    youtube: null;
} {
    return value == Platform.tv ? {
        tv: null
    } : value == Platform.instagram ? {
        instagram: null
    } : value == Platform.multiple ? {
        multiple: null
    } : value == Platform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): {
    often: null;
} | {
    rare: null;
} | {
    sometimes: null;
} {
    return value == Frequency.often ? {
        often: null
    } : value == Frequency.rare ? {
        rare: null
    } : value == Frequency.sometimes ? {
        sometimes: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdType): {
    fastFood: null;
} | {
    snacks: null;
} | {
    sugaryDrinks: null;
} {
    return value == AdType.fastFood ? {
        fastFood: null
    } : value == AdType.snacks ? {
        snacks: null
    } : value == AdType.sugaryDrinks ? {
        sugaryDrinks: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
